version: '3'

services:
  db:
    image: mysql:8.0.30
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: crud_nest_mysql
    volumes:
      - ./mysql-data:/var/lib/mysql